# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: required
cache: packages

os:
  - linux
  - osx

r:
  - release
  

notifications:
email:
on_success: change
on_failure: change
    

matrix:
  exclude:
    - r: devel
      os: osx

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=FALSE
    - ASAN="-fsanitize=address -fno-omit-frame-pointer"
    - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
    - HDF5_VERSION=1.8.17
    - HDF5_RELEASE_URL="https://support.hdfgroup.org/ftp/HDF5/releases"

before_install:

addons:
  apt:
    packages:
      - subversion
      - autoconf
      - build-essential
      - libtool
      - libmagick++-dev
  homebrew:
    packages:
      - libgit2

bioc_packages:
#  - GenomeInfoDbData
#  - DESeq2
#  - MAST
#  - S4Vectors
  - knitr
  - LoomExperiment
  - SummarizedExperiment
  - SingleCellExperiment

r_github_packages:
  - cellgeni/sceasy
  - rstudio/reticulate

after_success:
  - Rscript -e 'library(covr); codecov()'

warnings_are_errors: false